name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Check code quality with flake8
        run: |
          # Only check for syntax errors and undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check Python syntax
        run: |
          # Find all Python files and check their syntax
          find . -name "*.py" -type f -exec python -m py_compile {} +
